### ISSUE TITLE
RuntimeError: ECL says: Module error: Don't know how to REQUIRE MAXIMA

### ISSUE THREAD

**Issue by saraedum** [conda-forge/maxima-feedstock#9]
At https://github.com/conda-forge/sage-feedstock we are now seeing lots of `RuntimeError: ECL says: Module error: Don't know how to REQUIRE MAXIMA.` Do we need to pin ecl more strictly, i.e., use the same version when running maxima that we used to build maxima? Or is this something else?

**Comment by saraedum** [comment]
@embray  I know close to nothing about ecl and maxima. Any ideas?

**Comment by saraedum** [comment]
Upgrading to 16.1.3 fixes that issue (but causes lots of others.)

**Comment by embray** [comment]
> Upgrading to 16.1.3 fixes that issue (but causes lots of others.)

Ah, the song of our people :(

**Comment by embray** [comment]
I still have yet to actually try building Sage in conda.  If I try to follow the instructions to do that now, will I reproduce the issue?  If so then I can proceed to investigate (6.1.2 is an awfully precise pinning, which is unfortunate, and strange since I've usually found ECL to be pretty stable...)

**Comment by embray** [comment]
I'm still not very familiar with working with conda builds (at least these days--it's changed a lot since I last played with it).  It's not clear to me what the most effective procedure is for testing this.
